"""
Read COLMAP binary model files (cameras.bin, images.bin).

Provides the camera intrinsics and image extrinsics required for
orthorectifying multispectral band images using the DSM produced by SFM.
"""
from __future__ import annotations

import struct
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np


CAMERA_MODEL_IDS = {
    0: ("SIMPLE_PINHOLE", 3),
    1: ("PINHOLE", 4),
    2: ("SIMPLE_RADIAL", 4),
    3: ("RADIAL", 5),
    4: ("OPENCV", 8),
    5: ("OPENCV_FISHEYE", 8),
    6: ("FULL_OPENCV", 12),
    7: ("FOV", 5),
    8: ("SIMPLE_RADIAL_FISHEYE", 4),
    9: ("RADIAL_FISHEYE", 5),
    10: ("THIN_PRISM_FISHEYE", 12),
}


@dataclass
class ColmapCamera:
    """COLMAP camera intrinsics."""

    camera_id: int
    model_name: str
    width: int
    height: int
    params: np.ndarray

    @property
    def focal_length_x(self) -> float:
        """Focal length in x (pixels)."""
        if self.model_name == "SIMPLE_PINHOLE":
            return float(self.params[0])
        return float(self.params[0])

    @property
    def focal_length_y(self) -> float:
        """Focal length in y (pixels)."""
        if self.model_name in ("SIMPLE_PINHOLE", "SIMPLE_RADIAL", "SIMPLE_RADIAL_FISHEYE"):
            return float(self.params[0])
        return float(self.params[1])

    @property
    def principal_point_x(self) -> float:
        """Principal point x (pixels)."""
        if self.model_name == "SIMPLE_PINHOLE":
            return float(self.params[1])
        if self.model_name in ("PINHOLE", "OPENCV", "FULL_OPENCV", "THIN_PRISM_FISHEYE"):
            return float(self.params[2])
        return float(self.params[1])

    @property
    def principal_point_y(self) -> float:
        """Principal point y (pixels)."""
        if self.model_name == "SIMPLE_PINHOLE":
            return float(self.params[2])
        if self.model_name in ("PINHOLE", "OPENCV", "FULL_OPENCV", "THIN_PRISM_FISHEYE"):
            return float(self.params[3])
        return float(self.params[2])


@dataclass
class ColmapImage:
    """COLMAP image extrinsics (pose)."""

    image_id: int
    qvec: np.ndarray
    tvec: np.ndarray
    camera_id: int
    name: str

    def rotation_matrix(self) -> np.ndarray:
        """Convert quaternion (w, x, y, z) to 3×3 rotation matrix."""
        w, x, y, z = self.qvec
        return np.array([
            [1 - 2*y*y - 2*z*z, 2*x*y - 2*w*z, 2*x*z + 2*w*y],
            [2*x*y + 2*w*z, 1 - 2*x*x - 2*z*z, 2*y*z - 2*w*x],
            [2*x*z - 2*w*y, 2*y*z + 2*w*x, 1 - 2*x*x - 2*y*y],
        ])

    def projection_center(self) -> np.ndarray:
        """Camera center in world coordinates: C = -R^T @ t."""
        rot = self.rotation_matrix()
        return -rot.T @ self.tvec


def read_cameras_binary(path: Path) -> dict[int, ColmapCamera]:
    """
    Read cameras.bin generated by COLMAP.

    Args:
        path: Path to cameras.bin

    Returns:
        Mapping of camera_id → ColmapCamera
    """
    cameras: dict[int, ColmapCamera] = {}

    with open(path, "rb") as f:
        num_cameras = struct.unpack("<Q", f.read(8))[0]

        for _ in range(num_cameras):
            camera_id = struct.unpack("<I", f.read(4))[0]
            model_id = struct.unpack("<i", f.read(4))[0]
            width = struct.unpack("<Q", f.read(8))[0]
            height = struct.unpack("<Q", f.read(8))[0]

            model_name, num_params = CAMERA_MODEL_IDS.get(
                model_id, ("UNKNOWN", 0)
            )
            params = np.array(
                struct.unpack(f"<{num_params}d", f.read(8 * num_params))
            )

            cameras[camera_id] = ColmapCamera(
                camera_id=camera_id,
                model_name=model_name,
                width=width,
                height=height,
                params=params,
            )

    return cameras


def read_images_binary(path: Path) -> dict[int, ColmapImage]:
    """
    Read images.bin generated by COLMAP.

    Args:
        path: Path to images.bin

    Returns:
        Mapping of image_id → ColmapImage
    """
    images: dict[int, ColmapImage] = {}

    with open(path, "rb") as f:
        num_images = struct.unpack("<Q", f.read(8))[0]

        for _ in range(num_images):
            image_id = struct.unpack("<I", f.read(4))[0]
            qvec = np.array(struct.unpack("<4d", f.read(32)))
            tvec = np.array(struct.unpack("<3d", f.read(24)))
            camera_id = struct.unpack("<I", f.read(4))[0]

            name_bytes = b""
            while True:
                ch = f.read(1)
                if ch == b"\x00":
                    break
                name_bytes += ch
            name = name_bytes.decode("utf-8")

            num_points2d = struct.unpack("<Q", f.read(8))[0]
            f.read(num_points2d * 24)

            images[image_id] = ColmapImage(
                image_id=image_id,
                qvec=qvec,
                tvec=tvec,
                camera_id=camera_id,
                name=name,
            )

    return images
