# Generated by Django 5.1.14 on 2026-01-03 10:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploads', '0007_aiprocessingjob_type_alter_aiprocessingjob_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resolution_gsd', models.FloatField(help_text='GSD in cm/px')),
                ('radiometric_calibration', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('stage', models.CharField(choices=[('queued', 'Queued'), ('sfm', 'Structure from Motion'), ('mvs', 'Multi View Stereo'), ('publishing', 'Publishing')], default='queued', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(db_column='dataset_id', on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='uploads.dataset')),
            ],
            options={
                'db_table': 'jobs_processing_job',
            },
        ),
    ]
