# Generated by Django 5.2.9 on 2026-02-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_add_retry_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingjob',
            name='last_successful_stage',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('queued', 'Queued'), ('radiometric_calibration', 'Radiometric Calibration'), ('sfm', 'Structure from Motion'), ('orthomosaic', 'Orthomosaic Generation'), ('uploading', 'Uploading Results'), ('publishing', 'Publishing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], help_text='Last stage completed successfully (for resume on retry)', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='stage',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('radiometric_calibration', 'Radiometric Calibration'), ('sfm', 'Structure from Motion'), ('orthomosaic', 'Orthomosaic Generation'), ('uploading', 'Uploading Results'), ('publishing', 'Publishing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=30),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
