# Generated by Django 5.2.10 on 2026-03-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_add_analysis_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the job completed or failed', null=True),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When the job started processing', null=True),
        ),
    ]
