# Generated by Django 5.1.14 on 2025-12-27 14:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('s3_path_raw_images', models.CharField(help_text='S3 path to raw input images', max_length=1024)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('QUEUED', 'queued'), ('PROCESSING', 'processing'), ('COMPLETED', 'completed'), ('FAILED', 'failed')], default='PENDING', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('orthomosaic_url', models.URLField(blank=True, null=True)),
                ('mesh_model_url', models.URLField(blank=True, null=True)),
                ('dsm_url', models.URLField(blank=True, null=True)),
                ('ndvi_url', models.URLField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processings', to='processings.dataset')),
            ],
        ),
    ]
