"""
Multispectral band orthorectification using GPS and DSM geometry.

Orthorectifies calibrated reflectance images (per-band TIFs) onto the same
geographic grid as the RGB orthomosaic using:
  - Per-image GPS EXIF from the original source images
  - The DSM generated by the orthomosaic pipeline (for target CRS / extent)
  - GDAL gdalwarp for per-image geographic projection
  - gdal_merge for final mosaic with nodata-aware blending

Each reflectance image is placed at its correct GPS position (image centre)
and warped to the target UTM grid. This eliminates the horizontal banding
artifact that occurred when all images were naively resized to the full DSM
dimensions and blended without geographic positioning.
"""
from __future__ import annotations

import math
import os
import re
import subprocess
import tempfile
from pathlib import Path

import numpy as np

from services.orthomosaic_generation.app.core.algorithms.pose_ortho import (
    orthorectify_bands_pose,
)
from services.orthomosaic_generation.logger import logger

# Pose-driven orthorectification (project MS bands through the SFM RGB poses + DSM)
# replaces the GPS + nadir direct-georeferencing path, eliminating the "puzzle-piece"
# tile misplacement.  Opt-in until validated per dataset; auto-falls back to the GPS
# path when SFM pose artifacts are missing (e.g. non-SFM input).  See ADR 0002 §3.5.
_USE_POSE_ORTHO = os.environ.get("ORTHO_USE_POSE_ORTHO", "false").strip().lower() in (
    "1", "true", "yes",
)

try:
    from osgeo import gdal, osr

    gdal.UseExceptions()
except ImportError:
    gdal = None
    osr = None

try:
    from PIL import Image as _PILImage
    from PIL.ExifTags import GPSTAGS as _GPSTAGS
    from PIL.ExifTags import TAGS as _TAGS
except ImportError:
    _PILImage = None
    _TAGS = {}
    _GPSTAGS = {}

# AGL altitude used when no XMP/EXIF source is available.
# 30 m is a more conservative small-drone default than 100 m.
_DEFAULT_AGL_M: float = 30.0

# Horizontal FOV used as a last resort when all EXIF/XMP and model lookups fail.
# 65° is a rough mid-range value for small drone cameras.
_DEFAULT_HFOV_DEG: float = 65.0

# Known horizontal FOV per drone model, used when both EXIF and XMP lack focal data.
# Values are for the multispectral / main imaging sensor on each platform:
#   M3M  — DJI Mavic 3 Multispectral MS sensor, CalibratedFocalLength ≈3725 px @ 2592 px wide
#           → HFOV = 2·atan(2592/(2·3725)) ≈ 38.5°
#   P4M  — DJI Phantom 4 Multispectral, 5.74 mm lens, 1/2.9" sensor → HFOV ≈ 62.7°
_DRONE_MODEL_HFOV_DEG: dict[str, float] = {
    "M3M": 38.5,
    "M3T": 82.9,   # DJI Mavic 3 Thermal wide camera
    "M30": 79.0,   # DJI Matrice 30
    "P4M": 62.7,   # DJI Phantom 4 Multispectral
}

# NoData value written into intermediate warped TIFFs.
_NODATA: float = -9999.0

# Erosion applied to the DSM coverage mask before clipping band outputs.
# Removes the noisy perimeter of the reconstruction (sparse point cloud at
# field edges) which otherwise causes radial streaking in hillshade outputs.
# Units: pixels.  Increase if boundary artefacts are still visible.
_DSM_MASK_EROSION_PX: int = 15


SPECTRAL_BANDS = ["blue", "green", "red", "red_edge", "nir"]


# ---------------------------------------------------------------------------
# GPS helpers
# ---------------------------------------------------------------------------

def _dms_to_decimal(dms: tuple, ref: str) -> float:
    """Convert degrees-minutes-seconds EXIF tuple to signed decimal degrees."""
    d, m, s = dms
    value = float(d) + float(m) / 60.0 + float(s) / 3600.0
    if ref in ("S", "W"):
        value = -value
    return value


def _extract_gps_from_image(path: Path) -> tuple[float, float, float] | None:
    """
    Extract (latitude, longitude, altitude_m) from image GPS EXIF.

    Returns None when GPS data is absent or cannot be parsed.
    """
    if _PILImage is None:
        return None
    try:
        with _PILImage.open(str(path)) as img:
            exif = img.getexif()
            if not exif:
                return None
            gps_ifd = exif.get_ifd(0x8825)  # GPS IFD tag
            if not gps_ifd:
                return None
            gps = {_GPSTAGS.get(k, k): v for k, v in gps_ifd.items()}

            lat_dms = gps.get("GPSLatitude")
            lon_dms = gps.get("GPSLongitude")
            if lat_dms is None or lon_dms is None:
                return None

            lat = _dms_to_decimal(lat_dms, gps.get("GPSLatitudeRef", "N"))
            lon = _dms_to_decimal(lon_dms, gps.get("GPSLongitudeRef", "E"))

            alt_tag = gps.get("GPSAltitude")
            alt_m = float(alt_tag) if alt_tag is not None else 100.0
            if gps.get("GPSAltitudeRef", 0) == 1:
                alt_m = -alt_m

            return lat, lon, alt_m
    except Exception as exc:
        logger.debug(f"GPS extraction failed for {path.name}: {exc}")
        return None


def _extract_agl_hfov_yaw(
    orig_path: Path,
    image_width: int,
    dsm_info: dict,
    drone_model: str | None = None,
) -> tuple[float, float, float]:
    """
    Return ``(agl_m, hfov_deg, yaw_deg)`` for a single image.

    **AGL resolution order** (critical — GPSAltitude is AMSL, not AGL):

    1. XMP ``drone-dji:RelativeAltitude`` — RTK AGL, most accurate.
    2. XMP ``drone-dji:AbsoluteAltitude`` minus ``dsm_info["mean_elevation"]``.
    3. EXIF ``GPSAltitude`` minus ``dsm_info["mean_elevation"]``.
    4. ``_DEFAULT_AGL_M`` (30 m).

    **HFOV resolution order**:

    1. XMP ``drone-dji:CalibratedFocalLength`` (pixels) + ``image_width``.
    2. EXIF ``FocalLength`` + ``FocalPlaneXResolution`` / ``FocalPlaneResolutionUnit``.
    3. EXIF ``FocalLengthIn35mmFilm``.
    4. ``_DRONE_MODEL_HFOV_DEG`` lookup keyed by ``drone_model``.
    5. ``_DEFAULT_HFOV_DEG`` (65°).

    **Yaw resolution order**:

    1. XMP ``drone-dji:FlightYawDegree`` — drone body heading.
    2. XMP ``drone-dji:GimbalYawDegree`` — gimbal yaw (fallback for fixed-mount sensors).
    3. 0.0 (north-up, no rotation).
    """
    agl_m: float | None = None
    hfov_deg: float | None = None
    yaw_deg: float = 0.0
    dsm_mean_elev: float = dsm_info.get("mean_elevation", 0.0)

    # ------------------------------------------------------------------
    # 1. XMP (highest priority for AGL, focal length, and yaw)
    # ------------------------------------------------------------------
    try:
        with open(orig_path, "rb") as fh:
            raw = fh.read()
        xmp_start = raw.find(b"<x:xmpmeta")
        xmp_end = raw.find(b"</x:xmpmeta>")
        if xmp_start != -1 and xmp_end != -1:
            xmp = raw[xmp_start : xmp_end + 12].decode("utf-8", errors="ignore")

            # AGL: RelativeAltitude is the most direct
            m = re.search(r'drone-dji:RelativeAltitude="([+-]?\d+\.?\d*)"', xmp)
            if m:
                agl_m = abs(float(m.group(1)))
                logger.debug(f"{orig_path.name}: AGL from XMP RelativeAltitude = {agl_m:.2f} m")

            # AGL fallback: AbsoluteAltitude minus terrain
            if agl_m is None:
                m = re.search(r'drone-dji:AbsoluteAltitude="([+-]?\d+\.?\d*)"', xmp)
                if m:
                    agl_m = abs(float(m.group(1))) - dsm_mean_elev
                    logger.debug(
                        f"{orig_path.name}: AGL from XMP AbsoluteAltitude - DSM mean "
                        f"= {agl_m:.2f} m"
                    )

            # HFOV: CalibratedFocalLength is in pixels — exact per-image value
            m = re.search(r'drone-dji:CalibratedFocalLength="([\d.]+)"', xmp)
            if m:
                fl_px = float(m.group(1))
                if fl_px > 0:
                    hfov_deg = math.degrees(2.0 * math.atan(image_width / (2.0 * fl_px)))
                    logger.debug(
                        f"{orig_path.name}: HFOV from XMP CalibratedFocalLength "
                        f"({fl_px:.1f} px) = {hfov_deg:.2f}°"
                    )

            # Yaw: FlightYawDegree is the drone body heading (clockwise from north).
            # GimbalYawDegree is used as fallback for fixed-mount multispectral sensors
            # where the gimbal yaw equals the flight heading.
            m = re.search(r'drone-dji:FlightYawDegree="([+-]?\d+\.?\d*)"', xmp)
            if m:
                yaw_deg = float(m.group(1))
                logger.debug(f"{orig_path.name}: yaw from XMP FlightYawDegree = {yaw_deg:.2f}°")
            else:
                m = re.search(r'drone-dji:GimbalYawDegree="([+-]?\d+\.?\d*)"', xmp)
                if m:
                    yaw_deg = float(m.group(1))
                    logger.debug(
                        f"{orig_path.name}: yaw from XMP GimbalYawDegree = {yaw_deg:.2f}°"
                    )
    except Exception as exc:
        logger.debug(f"XMP read failed for {orig_path.name}: {exc}")

    # ------------------------------------------------------------------
    # 2. EXIF fallbacks
    # ------------------------------------------------------------------
    if (agl_m is None or hfov_deg is None) and _PILImage is not None:
        try:
            with _PILImage.open(str(orig_path)) as img:
                exif = img.getexif()
                if exif:
                    # AGL: GPSAltitude is AMSL — subtract DSM terrain elevation
                    if agl_m is None:
                        gps_ifd = exif.get_ifd(0x8825)
                        alt_tag = gps_ifd.get(0x0006)  # GPSAltitude
                        if alt_tag is not None:
                            alt_amsl = float(alt_tag)
                            if gps_ifd.get(0x0005, 0) == 1:  # GPSAltitudeRef below sea
                                alt_amsl = -alt_amsl
                            agl_m = alt_amsl - dsm_mean_elev
                            logger.debug(
                                f"{orig_path.name}: AGL from EXIF GPSAltitude "
                                f"({alt_amsl:.1f} m AMSL) - DSM mean "
                                f"({dsm_mean_elev:.1f} m) = {agl_m:.2f} m"
                            )

                    if hfov_deg is None:
                        exif_ifd = exif.get_ifd(0x8769)  # Exif SubIFD

                        focal_raw = exif_ifd.get(0x920A)  # FocalLength
                        if focal_raw is not None:
                            focal_mm = float(focal_raw)
                            if focal_mm > 0:
                                fplane_res = exif_ifd.get(0xA20E)  # FocalPlaneXResolution
                                fplane_unit = exif_ifd.get(0xA210, 2)  # 2=inch, 3=cm
                                if fplane_res is not None:
                                    # DJI stores this as a rational tuple in some firmware
                                    if isinstance(fplane_res, tuple):
                                        fplane_res = fplane_res[0] / fplane_res[1]
                                    else:
                                        fplane_res = float(fplane_res)
                                    if fplane_res > 0:
                                        unit_mm = 25.4 if fplane_unit == 2 else 10.0
                                        pixel_pitch_mm = unit_mm / fplane_res
                                        sensor_width_mm = image_width * pixel_pitch_mm
                                        hfov_deg = math.degrees(
                                            2.0 * math.atan(
                                                sensor_width_mm / (2.0 * focal_mm)
                                            )
                                        )
                                        logger.debug(
                                            f"{orig_path.name}: HFOV from EXIF "
                                            f"focal+fplane = {hfov_deg:.2f}°"
                                        )

                        if hfov_deg is None:
                            f35_raw = exif_ifd.get(0xA405)  # FocalLengthIn35mmFilm
                            if f35_raw is not None and float(f35_raw) > 0:
                                hfov_deg = math.degrees(
                                    2.0 * math.atan(18.0 / float(f35_raw))
                                )
                                logger.debug(
                                    f"{orig_path.name}: HFOV from EXIF "
                                    f"35mm-equivalent = {hfov_deg:.2f}°"
                                )
        except Exception as exc:
            logger.debug(f"EXIF read failed for {orig_path.name}: {exc}")

    # ------------------------------------------------------------------
    # 3. Model lookup / hard defaults
    # ------------------------------------------------------------------
    if agl_m is None or agl_m <= 0:
        logger.debug(
            f"{orig_path.name}: AGL fallback to default {_DEFAULT_AGL_M} m "
            "(no XMP/EXIF altitude source)"
        )
        agl_m = _DEFAULT_AGL_M

    if hfov_deg is None:
        if drone_model and drone_model in _DRONE_MODEL_HFOV_DEG:
            hfov_deg = _DRONE_MODEL_HFOV_DEG[drone_model]
            logger.debug(
                f"{orig_path.name}: HFOV from drone model lookup "
                f"({drone_model}) = {hfov_deg:.2f}°"
            )
        else:
            logger.debug(
                f"{orig_path.name}: HFOV fallback to default {_DEFAULT_HFOV_DEG}°"
            )
            hfov_deg = _DEFAULT_HFOV_DEG

    return agl_m, hfov_deg, yaw_deg


def _build_original_image_map(
    band_manifest: dict,
    band_name: str,
) -> dict[str, str]:
    """
    Build a mapping from image stem → original file path.

    Uses the bands → {band_name} → images list in the serialised
    DatasetBandManifest dict passed from the API gateway.
    """
    if not band_manifest or not isinstance(band_manifest, dict):
        return {}

    band_group = band_manifest.get("bands", {}).get(band_name)
    if not isinstance(band_group, dict):
        return {}

    result: dict[str, str] = {}
    for img_info in band_group.get("images", []):
        file_path = (
            img_info.get("file_path", "")
            if isinstance(img_info, dict)
            else getattr(img_info, "file_path", "")
        )
        if file_path:
            result[Path(file_path).stem] = file_path
    return result


def orthorectify_bands(
    calibration_path: str,
    sfm_run_path: str,
    dsm_path: str,
    output_dir: str,
    band_manifest: dict | None = None,
) -> dict[str, str]:
    """
    Orthorectify all spectral bands onto the DSM grid.

    For each band, the calibrated reflectance images are projected onto the
    DSM's geographic grid and mosaiced into a single-band GeoTIFF.

    When ``band_manifest`` is supplied (normal production path), each image is
    GPS-positioned using EXIF from the original source file and warped to the
    target UTM grid with ``gdalwarp``.  Images are then composited using
    distance-weighted feathering: each pixel contribution is weighted by its
    distance from the nearest nodata/edge pixel, so overlapping images blend
    smoothly and flight-line seam artifacts are eliminated.

    When ``band_manifest`` is absent, a legacy median-composite fallback is
    used instead.

    Args:
        calibration_path: Root of calibrated images (contains band subfolders)
        sfm_run_path: SFM run directory (reserved for future pose-based ortho)
        dsm_path: Path to the filled DSM GeoTIFF
        output_dir: Directory for output band ortho GeoTIFFs
        band_manifest: Serialised DatasetBandManifest dict from the API gateway.
                       Required for GPS-guided warping.

    Returns:
        Mapping of band_name → output GeoTIFF path
    """
    cal_root = Path(calibration_path)
    out_root = Path(output_dir)
    out_root.mkdir(parents=True, exist_ok=True)

    dsm_info = _read_dsm_metadata(Path(dsm_path))
    if dsm_info is None:
        raise RuntimeError(f"Cannot read DSM metadata from {dsm_path}")

    # Pose-driven path (preferred): project each band through the SFM RGB poses + DSM
    # so all bands co-register by construction.  Falls back to the GPS path below
    # when disabled or when the SFM pose artifacts are unavailable.
    if _USE_POSE_ORTHO and band_manifest:
        logger.info("Orthorectifying bands via SFM poses (pose-driven path)")
        pose_outputs = orthorectify_bands_pose(
            calibration_path=calibration_path,
            sfm_run_path=sfm_run_path,
            dsm_info=dsm_info,
            band_manifest=band_manifest,
            output_dir=output_dir,
            bands=SPECTRAL_BANDS,
            build_original_map=_build_original_image_map,
        )
        if pose_outputs:
            return pose_outputs
        logger.warning(
            "Pose-driven orthorectification unavailable (no SFM geometry) — "
            "falling back to GPS-guided warping."
        )

    outputs: dict[str, str] = {}

    # Pass 1 — warp every band's images and record per-image mean + GPS.  Warped
    # TIFs are kept on disk (one tmp dir per band) until the blend pass.  Strip
    # normalisation gains are computed ACROSS all bands afterwards, never
    # per-band, so a common per-image illumination factor cancels in NDVI/NDRE/
    # GNDVI instead of being injected into them as flight-line banding.
    band_warps: dict[str, list[dict]] = {}
    band_tmp_dirs: dict[str, Path] = {}
    band_out_paths: dict[str, Path] = {}

    # Build the inter-band registration reference: one image per capture from a
    # reference band, keyed by capture sequence.  NIR is preferred (highest
    # vegetation contrast → most reliable phase correlation); fall back to the
    # first available band.  Each band is registered to this reference per
    # capture before warping so all bands share one ground footprint.
    reference_band = next(
        (b for b in ("nir", "red_edge", "red", "green") if (cal_root / b).is_dir()),
        None,
    )
    reference_map: dict[str, Path] = {}
    if reference_band is not None:
        ref_dir = cal_root / reference_band
        ref_tifs = sorted(ref_dir.glob("*_reflectance.tif")) or sorted(ref_dir.glob("*.tif"))
        reference_map = {_capture_key(p): p for p in ref_tifs}
        logger.info(
            f"Inter-band registration reference: {reference_band} "
            f"({len(reference_map)} captures)"
        )

    try:
        for band_name in SPECTRAL_BANDS:
            band_dir = cal_root / band_name
            if not band_dir.is_dir():
                logger.info(f"No calibrated images for band {band_name}, skipping")
                continue

            tifs = sorted(band_dir.glob("*_reflectance.tif"))
            if not tifs:
                tifs = sorted(band_dir.glob("*.tif"))
            if not tifs:
                logger.warning(f"No TIF files found in {band_dir}")
                continue

            original_map = _build_original_image_map(band_manifest, band_name)
            if not original_map:
                raise RuntimeError(
                    f"band_manifest missing original image paths for band '{band_name}'. "
                    "GPS-guided warping is required for correct multispectral alignment. "
                    "Ensure band_manifest is populated with source image file paths before "
                    "calling orthorectify_bands."
                )

            logger.info(
                f"Orthorectifying {len(tifs)} {band_name} images "
                f"({len(original_map)} original image paths available)"
            )

            # Keep warps on the output workspace volume (not /tmp): all bands'
            # warps are held until the shared-gain blend pass, which is more
            # temp data than the old per-band flow, and the job workspace has the
            # room the small system /tmp may not.
            tmp_dir = Path(tempfile.mkdtemp(prefix=f"ortho_gps_{band_name}_", dir=out_root))
            warped = _warp_band_images(
                tifs, dsm_info, original_map, tmp_dir, reference_map=reference_map,
            )
            if not warped:
                tmp_dir.rmdir()
                raise RuntimeError(
                    f"GPS composite failed for band '{band_name}': no images "
                    "could be warped. Check that original source image paths "
                    "are accessible and contain GPS EXIF."
                )

            band_warps[band_name] = warped
            band_tmp_dirs[band_name] = tmp_dir
            band_out_paths[band_name] = out_root / f"{band_name}_ortho.tif"

        if not band_warps:
            return outputs

        # Compute one shared per-image gain across all bands.  Strip identity is
        # geometric (band-independent); the gain corrects a single physical
        # per-pass illumination change that scales every band equally.
        all_stems: list[str] = []
        stem_latlon: dict[str, tuple[float, float]] = {}
        band_means: dict[str, dict[str, float]] = {}
        for band_name, warped in band_warps.items():
            band_means[band_name] = {it["stem"]: it["mean"] for it in warped}
            for it in warped:
                if it["stem"] not in stem_latlon:
                    stem_latlon[it["stem"]] = (it["lat"], it["lon"])
                    all_stems.append(it["stem"])

        lats = np.array([stem_latlon[s][0] for s in all_stems])
        lons = np.array([stem_latlon[s][1] for s in all_stems])
        gains_by_stem = _compute_shared_strip_gains(
            all_stems, lats, lons, band_means
        )

        # Pass 2 — apply the shared gains and feather-blend each band.
        for band_name, warped in band_warps.items():
            out_path = band_out_paths[band_name]
            _blend_band_with_gains(warped, gains_by_stem, out_path, dsm_info)
            outputs[band_name] = str(out_path)
            logger.info(f"Band {band_name} ortho: {out_path}")

    finally:
        for tmp_dir in band_tmp_dirs.values():
            for f in tmp_dir.glob("*.tif"):
                f.unlink(missing_ok=True)
            try:
                tmp_dir.rmdir()
            except OSError:
                pass  # non-empty on failure, leave for diagnosis

    return outputs


def stack_bands(
    band_paths: dict[str, str],
    output_path: str,
) -> str:
    """
    Stack single-band ortho GeoTIFFs into a multi-band GeoTIFF.

    Band order: Green, Red, RedEdge, NIR (bands 1-4).

    Args:
        band_paths: Mapping of band_name → single-band GeoTIFF path
        output_path: Destination for the stacked multi-band GeoTIFF

    Returns:
        Path to the stacked GeoTIFF
    """
    ordered = [
        band_paths[b] for b in SPECTRAL_BANDS if b in band_paths
    ]
    if not ordered:
        raise ValueError("No band orthos to stack")

    cmd = [
        "gdal_merge.py",
        "-separate",
        "-o", output_path,
        "-co", "COMPRESS=DEFLATE",
        "-co", "TILED=YES",
        "-co", "BIGTIFF=YES",
        "-ot", "Float32",
    ] + ordered

    logger.info(f"Stacking {len(ordered)} bands into {output_path}")
    _run_cmd(cmd, "band stacking")

    return output_path


# ---------------------------------------------------------------------------
# GPS-guided composite (primary path)
# ---------------------------------------------------------------------------

def _assign_flight_strips(
    lats: np.ndarray, lons: np.ndarray
) -> tuple[np.ndarray, int]:
    """
    Assign each image to a flight strip from its GPS coordinates.

    Flight strips are detected by projecting GPS coordinates onto the
    cross-track direction (found via PCA) and splitting at gaps that are large
    relative to the typical intra-strip cross-track step.

    Strip identity is a purely geometric property of the flight path and is
    therefore **band-independent** — the same image belongs to the same strip
    in every spectral band.  Keeping strip assignment separate from gain
    computation lets the caller derive a single per-image gain shared across
    all bands (see ``_compute_shared_strip_gains``), which is what preserves
    the ratio invariance of NDVI/NDRE/GNDVI.

    Args:
        lats: Per-image latitude (degrees)
        lons: Per-image longitude (degrees)

    Returns:
        Tuple of (strip_id array of length n, n_strips).  When fewer than two
        strips can be resolved, returns all-zero ids and ``n_strips == 1``.
    """
    n = len(lats)
    if n < 2:
        return np.zeros(n, dtype=int), 1

    cos_lat = np.cos(np.radians(lats.mean()))
    coords_m = np.column_stack([lats * 111320.0, lons * 111320.0 * cos_lat])

    centred = coords_m - coords_m.mean(axis=0)
    try:
        _, _, Vt = np.linalg.svd(centred, full_matrices=False)
    except np.linalg.LinAlgError:
        return np.zeros(n, dtype=int), 1
    cross_track_vec = Vt[1]           # second right-singular vector
    proj = centred @ cross_track_vec  # 1-D projection in metres

    sort_idx = np.argsort(proj)
    sorted_proj = proj[sort_idx]
    gaps = np.diff(sorted_proj)
    if len(gaps) == 0:
        return np.zeros(n, dtype=int), 1

    # Threshold is derived from the *typical* (intra-strip) cross-track gap, i.e.
    # the median of ALL gaps — which is dominated by the many small within-strip
    # steps, not the few large between-strip jumps.  A boundary is a gap that is
    # both ≥ 6× that typical step AND ≥ 5 m absolute.  Using the median of all
    # gaps (rather than only gaps > 0.5 m) avoids the failure mode where, with
    # low cross-track GPS jitter, the only surviving gaps are the between-strip
    # ones — which would make a "median × 3" threshold larger than the gaps
    # themselves and collapse everything into a single strip.
    typical_gap = float(np.median(gaps))
    gap_threshold = max(typical_gap * 6.0, 5.0)

    strip_ids_sorted = np.zeros(n, dtype=int)
    current_strip = 0
    for i, g in enumerate(gaps):
        if g > gap_threshold:
            current_strip += 1
        strip_ids_sorted[i + 1] = current_strip
    n_strips = current_strip + 1

    strip_id = np.empty(n, dtype=int)
    for rank, orig in enumerate(sort_idx):
        strip_id[orig] = strip_ids_sorted[rank]
    return strip_id, n_strips


def _compute_shared_strip_gains(
    stems: list[str],
    lats: np.ndarray,
    lons: np.ndarray,
    band_means: dict[str, dict[str, float]],
) -> dict[str, float]:
    """
    Compute one per-image gain shared across **all** bands.

    The historical bug behind the recurring NDVI flight-line banding was that a
    separate ``global_median / strip_mean`` gain was computed independently for
    each band.  Because the Red and NIR per-strip means differ, the per-band
    gains differed, and applying different multiplicative factors to Red and NIR
    changes the value of ``(NIR - Red) / (NIR + Red)`` — i.e. it injects banding
    straight into NDVI, which is supposed to be invariant to a *common*
    illumination factor.

    The fix: a flight strip is brighter or darker because of a single physical
    cause (sun-sensor / exposure for that pass), which scales *every* band by the
    same factor.  So we estimate one gain per strip from a band-averaged
    luminance and apply that identical gain to the image in every band.  A common
    factor cancels in every normalised-difference index, eliminating the banding
    while still flattening true strip-to-strip illumination steps.

    Args:
        stems: Per-image stem identifiers (band-independent image key)
        lats: Per-image latitude (degrees), aligned with ``stems``
        lons: Per-image longitude (degrees), aligned with ``stems``
        band_means: ``band_name → {stem → mean reflectance}`` from Pass 1 of
                    every band's warp

    Returns:
        Mapping of image stem → shared gain factor (1.0 = no correction)
    """
    n = len(stems)
    if n < 2:
        return {stem: 1.0 for stem in stems}

    strip_id, n_strips = _assign_flight_strips(lats, lons)
    if n_strips < 2:
        return {stem: 1.0 for stem in stems}

    # Band-averaged luminance per image: normalise each band by its own global
    # mean first so a bright band (NIR) does not dominate the average, then take
    # the mean of the available normalised band values for that image.
    band_global_mean: dict[str, float] = {}
    for band, per_stem in band_means.items():
        vals = [v for v in per_stem.values() if v > 0]
        band_global_mean[band] = float(np.mean(vals)) if vals else 0.0

    luminance = np.zeros(n, dtype=np.float64)
    for idx, stem in enumerate(stems):
        norm_vals = []
        for band, per_stem in band_means.items():
            g = band_global_mean.get(band, 0.0)
            v = per_stem.get(stem)
            if v is not None and v > 0 and g > 0:
                norm_vals.append(v / g)
        luminance[idx] = float(np.mean(norm_vals)) if norm_vals else 0.0

    strip_sum = np.zeros(n_strips, dtype=np.float64)
    strip_cnt = np.zeros(n_strips, dtype=int)
    for i in range(n):
        if luminance[i] > 0:
            strip_sum[strip_id[i]] += luminance[i]
            strip_cnt[strip_id[i]] += 1

    strip_means = np.where(strip_cnt > 0, strip_sum / np.maximum(strip_cnt, 1), 0.0)
    valid_mask = strip_cnt > 0
    if not valid_mask.any():
        return {stem: 1.0 for stem in stems}
    global_median = float(np.median(strip_means[valid_mask]))

    logger.info(
        f"Shared strip normalization (cross-band): {n_strips} strips, "
        f"luminance means {[round(float(m), 4) for m in strip_means[valid_mask]]}, "
        f"target median = {global_median:.4f}"
    )

    gains: dict[str, float] = {}
    for i, stem in enumerate(stems):
        sm = strip_means[strip_id[i]]
        gains[stem] = global_median / sm if sm > 0 else 1.0
    return gains


def _edge_distance_weight(valid: np.ndarray) -> np.ndarray:
    """
    Compute a smooth feathering weight for each valid pixel.

    For each valid pixel, returns the minimum of its distances (in pixel units)
    to the nearest invalid/nodata pixel in the four cardinal directions.  This
    produces a "tent" profile that peaks at image centres and fades to zero at
    image edges, enabling smooth blending when multiple images overlap.

    Implementation uses the "running-reset cumsum" trick — fully vectorised
    with NumPy, no scipy required.

    Args:
        valid: Boolean mask (True = valid pixel, False = nodata/invalid)

    Returns:
        Float32 weight array; 0 for invalid pixels, ≥ 1 for valid pixels.
    """
    v = valid.astype(np.int32)

    def _fwd_dist(arr2d: np.ndarray) -> np.ndarray:
        """Running distance to nearest 0 going left→right along axis=1."""
        cs = np.cumsum(arr2d, axis=1)
        # At each zero-position record the cumulative-sum value there,
        # then propagate it forward with a running maximum.
        baseline = np.where(arr2d == 0, cs, 0)
        np.maximum.accumulate(baseline, axis=1, out=baseline)
        return (cs - baseline) * arr2d

    left_d  = _fwd_dist(v)
    right_d = _fwd_dist(v[:, ::-1])[:, ::-1]
    top_d   = _fwd_dist(v.T).T
    bot_d   = _fwd_dist(v[::-1].T).T[::-1]

    return np.minimum(np.minimum(left_d, right_d),
                      np.minimum(top_d,  bot_d)).astype(np.float32)


def _phase_correlation_shift(
    ref: np.ndarray, mov: np.ndarray, max_shift_px: int = 40
) -> tuple[int, int]:
    """
    Estimate the integer (dy, dx) pixel shift that aligns ``mov`` onto ``ref``.

    Uses FFT phase correlation (numpy only — no OpenCV/scipy).  Both inputs are
    mean-removed so the DC term does not dominate.  The peak of the inverse FFT
    of the normalised cross-power spectrum gives the shift.  Shifts larger than
    ``max_shift_px`` are rejected (returns 0,0) as unreliable — the true
    inter-band offset on an M3M is a few px to ~15 px, so a large "shift" means
    the correlation peak is noise (e.g. near-empty overlap).

    Args:
        ref: Reference band array (e.g. NIR), same shape as ``mov``
        mov: Band array to be aligned to ``ref``
        max_shift_px: Reject/clamp shifts beyond this magnitude

    Returns:
        (dy, dx) integer shift to apply to ``mov`` (np.roll convention)
    """
    if ref.shape != mov.shape:
        return 0, 0
    a = np.nan_to_num(ref - float(np.nanmean(ref)))
    b = np.nan_to_num(mov - float(np.nanmean(mov)))
    F = np.fft.fft2(a)
    G = np.fft.fft2(b)
    R = F * np.conj(G)
    R /= np.abs(R) + 1e-12
    corr = np.fft.ifft2(R).real
    dy, dx = np.unravel_index(int(np.argmax(corr)), corr.shape)
    if dy > ref.shape[0] // 2:
        dy -= ref.shape[0]
    if dx > ref.shape[1] // 2:
        dx -= ref.shape[1]
    if abs(dy) > max_shift_px or abs(dx) > max_shift_px:
        return 0, 0
    return int(dy), int(dx)


def _warp_reflectance_image(
    refl_path: Path,
    orig_path: str,
    dsm_info: dict,
    warped_out: Path,
    tmp_dir: Path,
    gps: tuple[float, float, float] | None = None,
    reference_refl_path: Path | None = None,
) -> bool:
    """
    GPS-position a single reflectance TIFF and warp it to the target UTM grid.

    Steps:
      1. Extract GPS (lat, lon, alt) from the original source image (skipped
         when the caller already supplies ``gps``).
      2. Compute approximate GSD using altitude + assumed camera HFOV.
      3. Assign a WGS84 geotransform to the reflectance array and write a
         temporary GeoTIFF.
      4. Run gdalwarp to project into the target UTM CRS and grid extent.

    KNOWN LIMITATION — nadir assumption (camera tilt ignored).
        This is direct georeferencing: the image is placed at its GPS position
        and rotated only by *yaw* (``FlightYawDegree``).  Body **roll** and
        **pitch** are NOT applied, so the footprint is assumed perfectly nadir.
        On the DJI M3M the multispectral sensors are body-fixed (only the RGB
        camera is gimballed), so the MS bands actually tilt with the flight
        attitude — a ~10° roll at 12 m AGL shifts the footprint centre by
        ~2 m and skews it into a non-axis-aligned quad.  Correcting this needs a
        full collinearity / homography projection using
        ``FlightRollDegree`` + ``FlightPitchDegree`` (+ AGL), not a geotransform.
        Until then, residual per-image misregistration of up to a few GSD is
        expected on tilted captures; on gimbal-stabilised or low-wind flights
        the tilt is small.  See docs/changelogs for the rationale.

        Note also that this path uses raw EXIF GPS, NOT the PPK/MRK-upgraded
        positions used by the SFM geo-registration — another accuracy gap for
        the MS warp specifically.

    Args:
        gps: Pre-extracted (lat, lon, alt_m) tuple.  When supplied the
             internal EXIF read is skipped, saving one file open per image.

    Returns:
        True on success, False if GPS is unavailable or any step fails.
    """
    if gdal is None or osr is None:
        return False

    # --- 1. GPS ---
    if gps is None:
        gps = _extract_gps_from_image(Path(orig_path))
    if gps is None:
        logger.debug(f"No GPS for {Path(orig_path).name}, skipping")
        return False
    lat, lon, _alt_amsl = gps  # GPSAltitude is AMSL — AGL resolved below

    # --- 2. Source dimensions ---
    src_ds = gdal.Open(str(refl_path), gdal.GA_ReadOnly)
    if src_ds is None:
        return False
    src_w = src_ds.RasterXSize
    src_h = src_ds.RasterYSize
    data = src_ds.GetRasterBand(1).ReadAsArray().astype(np.float32)
    src_ds = None

    # --- 2b. Inter-band co-registration (per capture) ---
    # The M3M's spectral lenses are physically offset, so warping each band with
    # the same GPS/nadir geometry lands them at different ground positions
    # (measured constant ~(−12,−6) px offset).  Differencing misregistered bands
    # is the dominant source of vegetation-index noise.  Align this band to the
    # reference band (same capture) by an integer phase-correlation shift BEFORE
    # warping, so all bands of a capture share one footprint.  The reference band
    # registers against itself → zero shift (no-op).
    if reference_refl_path is not None and reference_refl_path != refl_path:
        ref_ds = gdal.Open(str(reference_refl_path), gdal.GA_ReadOnly)
        if ref_ds is not None:
            ref_data = ref_ds.GetRasterBand(1).ReadAsArray()
            ref_ds = None
            if ref_data is not None and ref_data.shape == data.shape:
                dy, dx = _phase_correlation_shift(
                    ref_data.astype(np.float32), data
                )
                if dy or dx:
                    # Shift band onto reference; vacated edges become nodata.
                    data = np.roll(np.roll(data, dy, axis=0), dx, axis=1)
                    if dy > 0:
                        data[:dy, :] = _NODATA
                    elif dy < 0:
                        data[dy:, :] = _NODATA
                    if dx > 0:
                        data[:, :dx] = _NODATA
                    elif dx < 0:
                        data[:, dx:] = _NODATA
                    logger.debug(
                        f"{refl_path.name}: band-registration shift "
                        f"dy={dy} dx={dx} px to reference {reference_refl_path.name}"
                    )

    # --- 3. AGL, HFOV, and yaw from XMP / EXIF / model lookup ---
    # GPSAltitude (EXIF) is AMSL.  For a field at ~90 m AMSL with the drone
    # at 95 m AMSL the true AGL is only ~5 m — using AMSL directly would give
    # an 8-19× error in computed footprint size.  _extract_agl_hfov_yaw reads
    # XMP RelativeAltitude first, then falls back to AMSL - DSM mean.
    agl_m, hfov_deg, yaw_deg = _extract_agl_hfov_yaw(Path(orig_path), src_w, dsm_info)
    hfov_rad = math.radians(hfov_deg)
    # Ground distance covered by the full image width
    ground_width_m = 2.0 * agl_m * math.tan(hfov_rad / 2.0)
    gsd_m = ground_width_m / src_w
    # Convert to degrees
    lat_rad = math.radians(lat)
    px_deg_x = gsd_m / (111320.0 * math.cos(lat_rad))
    px_deg_y = gsd_m / 111320.0

    # --- 4. Assign WGS84 geotransform with yaw rotation ---
    # GDAL geotransform rotation terms (gt[2], gt[4]) encode the image axes
    # in geographic space.  Without them every image is forced north-up,
    # misregistering footprints by up to several pixels at image corners when
    # the drone is not flying due north.  yaw_deg is clockwise from north.
    yaw_rad = math.radians(yaw_deg)
    cos_y = math.cos(yaw_rad)
    sin_y = math.sin(yaw_rad)
    # GDAL geotransform: X(col,row) = gt[0] + col*gt[1] + row*gt[2]
    #                    Y(col,row) = gt[3] + col*gt[4] + row*gt[5]
    # We want X(half_w, half_h) == lon, Y(half_w, half_h) == lat.
    # So:  ul_lon = lon - half_w*gt[1] - half_h*gt[2]
    #      ul_lat = lat - half_w*gt[4] - half_h*gt[5]
    half_w = src_w / 2.0
    half_h = src_h / 2.0
    gt1 =  px_deg_x * cos_y   # column step in longitude
    gt2 = -px_deg_y * sin_y   # row step in longitude    (rotation term)
    gt4 =  px_deg_x * sin_y   # column step in latitude  (rotation term)
    gt5 = -px_deg_y * cos_y   # row step in latitude
    ul_lon = lon - half_w * gt1 - half_h * gt2
    ul_lat = lat - half_w * gt4 - half_h * gt5
    src_gt = (ul_lon, gt1, gt2, ul_lat, gt4, gt5)

    geo_tif = tmp_dir / f"geo_{refl_path.stem}.tif"
    driver = gdal.GetDriverByName("GTiff")
    geo_ds = driver.Create(str(geo_tif), src_w, src_h, 1, gdal.GDT_Float32)
    geo_ds.SetGeoTransform(src_gt)
    epsg4326 = osr.SpatialReference()
    epsg4326.ImportFromEPSG(4326)
    geo_ds.SetProjection(epsg4326.ExportToWkt())
    band = geo_ds.GetRasterBand(1)
    band.WriteArray(data)
    band.SetNoDataValue(_NODATA)
    geo_ds.FlushCache()
    geo_ds = None

    # --- 5. gdalwarp to target UTM grid ---
    gt = dsm_info["geotransform"]
    xmin = gt[0]
    ymax = gt[3]
    xmax = xmin + dsm_info["width"] * gt[1]
    ymin = ymax + dsm_info["height"] * gt[5]  # gt[5] is negative
    res = abs(gt[1])

    cmd = [
        "gdalwarp",
        "-s_srs", "EPSG:4326",
        "-t_srs", dsm_info["projection"],
        "-te", str(xmin), str(ymin), str(xmax), str(ymax),
        "-tr", str(res), str(res),
        # Nearest-neighbour preserves the exact footprint boundary with no edge
        # erosion.  Bilinear + UNIFIED_SRC_NODATA erodes the valid footprint by
        # 1 px on every edge (the 2×2 kernel discards any pixel touching nodata),
        # producing the staircase outline visible around each image contribution.
        # Smooth blending is done by the distance-weighted feathering composite,
        # not by the per-image resampler.
        "-r", "near",
        "-srcnodata", str(_NODATA),
        "-dstnodata", str(_NODATA),
        "-wo", "UNIFIED_SRC_NODATA=YES",
        "-co", "COMPRESS=DEFLATE",
        str(geo_tif),
        str(warped_out),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    geo_tif.unlink(missing_ok=True)

    if result.returncode != 0:
        logger.warning(
            f"gdalwarp failed for {refl_path.name}: {result.stderr[:300]}"
        )
        return False
    return True


def _capture_key(refl_path: Path) -> str:
    """
    Return the DJI capture sequence key shared by all bands of one exposure.

    DJI multispectral filenames embed a 4-digit capture index, e.g.
    ``DJI_20240719091257_0001_MS_NIR_reflectance.tif`` → ``0001``.  All four
    bands of a capture share this key, so it links a band image to the reference
    band of the same exposure for inter-band registration.  Falls back to the
    full stem when the pattern is absent.
    """
    m = re.search(r"_(\d{4})_MS_", refl_path.name)
    return m.group(1) if m else refl_path.stem


def _warp_band_images(
    image_paths: list[Path],
    dsm_info: dict,
    original_image_map: dict[str, str],
    tmp_dir: Path,
    reference_map: dict[str, Path] | None = None,
) -> list[dict]:
    """
    Pass 1 of the GPS composite: GPS-warp every reflectance image of one band
    onto the DSM UTM grid and record its mean reflectance and GPS position.

    Warped TIFs are persisted in ``tmp_dir`` (one dir per band) so the blend
    pass can reload them after the shared cross-band gains have been computed.

    Args:
        image_paths: Calibrated reflectance TIFFs for one band
        dsm_info: DSM metadata (width, height, geotransform, projection)
        original_image_map: Mapping of image stem → original source file path
        tmp_dir: Directory in which warped TIFs are kept until the blend pass
        reference_map: Optional ``capture_key → reference-band reflectance path``
            (e.g. NIR per capture).  When given, each band image is phase-
            correlation-registered to its capture's reference band before warping
            so all bands share one ground footprint (fixes inter-band
            misregistration that otherwise corrupts vegetation indices).

    Returns:
        List of ``{path, stem, mean, lat, lon}`` dicts for the images that
        warped successfully with a positive mean reflectance.
    """
    if gdal is None:
        raise RuntimeError("GDAL Python bindings are required for GPS composite")

    warped_items: list[dict] = []
    skipped_nonpositive = 0

    for refl_path in image_paths:
        stem = refl_path.stem
        if stem.endswith("_reflectance"):
            stem = stem[: -len("_reflectance")]

        orig_path = original_image_map.get(stem)
        if not orig_path:
            logger.debug(
                f"No original image for {refl_path.name} (stem={stem!r}), skipping"
            )
            continue

        gps = _extract_gps_from_image(Path(orig_path))
        if gps is None:
            logger.debug(f"No GPS for {Path(orig_path).name}, skipping")
            continue
        gps_lat, gps_lon, _ = gps

        ref_refl = (
            reference_map.get(_capture_key(refl_path)) if reference_map else None
        )

        warped_out = tmp_dir / f"warped_{refl_path.stem}.tif"
        ok = _warp_reflectance_image(
            refl_path, orig_path, dsm_info, warped_out, tmp_dir, gps=gps,
            reference_refl_path=ref_refl,
        )
        if not ok or not warped_out.exists():
            continue

        warp_ds = gdal.Open(str(warped_out), gdal.GA_ReadOnly)
        if warp_ds is None:
            warped_out.unlink(missing_ok=True)
            continue
        data = warp_ds.GetRasterBand(1).ReadAsArray().astype(np.float32)
        warp_ds = None

        valid = (data != _NODATA) & np.isfinite(data)
        if not valid.any():
            warped_out.unlink(missing_ok=True)
            continue

        img_mean = float(data[valid].mean())
        if img_mean <= 0:
            warped_out.unlink(missing_ok=True)
            skipped_nonpositive += 1
            continue

        warped_items.append(
            {
                "path": warped_out,
                "stem": stem,
                "mean": img_mean,
                "lat": gps_lat,
                "lon": gps_lon,
            }
        )

    if skipped_nonpositive > 0:
        logger.warning(
            f"{skipped_nonpositive} image(s) had non-positive mean reflectance "
            "and were excluded from strip detection."
        )

    return warped_items


def _blend_band_with_gains(
    warped_items: list[dict],
    gains_by_stem: dict[str, float],
    output_path: Path,
    dsm_info: dict,
) -> None:
    """
    Pass 2 of the GPS composite: apply the shared per-image strip gain and
    feather-blend the warped images of one band into the final ortho.

    The gain applied to each image is looked up by stem from ``gains_by_stem``,
    which was computed **once across all bands** (see
    ``_compute_shared_strip_gains``).  Because the same image receives the same
    multiplicative factor in every band, the factor cancels in NDVI/NDRE/GNDVI
    and cannot introduce flight-line banding into the indices.

    Args:
        warped_items: Output of ``_warp_band_images`` for this band
        gains_by_stem: Shared image-stem → gain mapping (1.0 = no correction)
        output_path: Destination GeoTIFF
        dsm_info: DSM metadata (width, height, geotransform, projection, coverage_mask)
    """
    if gdal is None:
        raise RuntimeError("GDAL Python bindings are required for GPS composite")

    h = dsm_info["height"]
    w = dsm_info["width"]
    weighted_sum = np.zeros((h, w), dtype=np.float64)
    weight_total = np.zeros((h, w), dtype=np.float64)

    for item in warped_items:
        warp_ds = gdal.Open(str(item["path"]), gdal.GA_ReadOnly)
        if warp_ds is None:
            continue
        data = warp_ds.GetRasterBand(1).ReadAsArray().astype(np.float32)
        warp_ds = None
        item["path"].unlink(missing_ok=True)

        valid = (data != _NODATA) & np.isfinite(data)
        # Zero out nodata before multiplication so that isolated invalid pixels
        # (which receive a nonzero feathering weight from surrounding valid
        # pixels) cannot contribute -9999 into weighted_sum.
        data[~valid] = 0.0
        gain = np.float32(gains_by_stem.get(item["stem"], 1.0))
        data[valid] *= gain

        weight = _edge_distance_weight(valid)
        weighted_sum += data * weight
        weight_total += weight

    logger.info(
        f"Feather-blending {len(warped_items)} strip-normalised images → {output_path.name}"
    )

    with np.errstate(invalid="ignore", divide="ignore"):
        composite = np.where(
            weight_total > 0,
            (weighted_sum / weight_total).astype(np.float32),
            _NODATA,
        ).astype(np.float32)

    coverage_mask = dsm_info.get("coverage_mask")
    if coverage_mask is not None:
        composite = np.where(coverage_mask, composite, _NODATA)

    driver = gdal.GetDriverByName("GTiff")
    gt = dsm_info["geotransform"]
    out_ds = driver.Create(
        str(output_path), w, h, 1, gdal.GDT_Float32,
        options=["COMPRESS=DEFLATE", "TILED=YES", "BIGTIFF=YES"],
    )
    out_ds.SetGeoTransform(gt)
    out_ds.SetProjection(dsm_info["projection"])
    band_obj = out_ds.GetRasterBand(1)
    band_obj.WriteArray(composite)
    band_obj.SetNoDataValue(_NODATA)
    out_ds.FlushCache()
    out_ds = None


# ---------------------------------------------------------------------------
# Fallback: legacy median composite
# ---------------------------------------------------------------------------

def _median_composite_band(
    image_paths: list[Path],
    output_path: Path,
    dsm_info: dict,
) -> None:
    """
    Fallback: create a median composite of reflectance images for one band.

    Used only when original source image paths are unavailable (so GPS-guided
    warping cannot be performed). All images are resized to the DSM pixel
    dimensions and blended by median — this produces correct CRS metadata but
    may exhibit horizontal banding for multi-strip surveys.

    Args:
        image_paths: Per-image reflectance TIFs
        output_path: Destination GeoTIFF
        dsm_info: DSM metadata (width, height, geotransform, projection)
    """
    if gdal is None:
        raise RuntimeError("GDAL Python bindings are required")

    arrays: list[np.ndarray] = []
    for p in image_paths:
        ds = gdal.Open(str(p), gdal.GA_ReadOnly)
        if ds is None:
            logger.warning(f"Cannot open {p}, skipping")
            continue
        arr = ds.GetRasterBand(1).ReadAsArray().astype(np.float32)
        arrays.append(arr)
        ds = None

    if not arrays:
        raise RuntimeError("No valid images to composite")

    target_h = dsm_info["height"]
    target_w = dsm_info["width"]

    resized: list[np.ndarray] = []
    for arr in arrays:
        if arr.shape == (target_h, target_w):
            resized.append(arr)
        else:
            from PIL import Image

            pil = Image.fromarray(arr)
            # Image.BILINEAR was removed in Pillow 10; use Resampling enum.
            resample = getattr(Image, "Resampling", Image).BILINEAR
            pil_resized = pil.resize((target_w, target_h), resample)
            resized.append(np.array(pil_resized, dtype=np.float32))

    stack = np.stack(resized, axis=0)
    median = np.median(stack, axis=0).astype(np.float32)

    # Clip to DSM field boundary — same as GPS composite path.
    coverage_mask = dsm_info.get("coverage_mask")
    if coverage_mask is not None:
        median = np.where(coverage_mask, median, _NODATA)

    driver = gdal.GetDriverByName("GTiff")
    out_ds = driver.Create(
        str(output_path),
        target_w,
        target_h,
        1,
        gdal.GDT_Float32,
        options=["COMPRESS=DEFLATE", "TILED=YES"],
    )
    out_ds.SetGeoTransform(dsm_info["geotransform"])
    out_ds.SetProjection(dsm_info["projection"])
    out_ds.GetRasterBand(1).WriteArray(median)
    out_ds.GetRasterBand(1).SetNoDataValue(_NODATA)
    out_ds.FlushCache()
    out_ds = None

    logger.info(
        f"Median composite written: {output_path} "
        f"({target_w}×{target_h}, float32)"
    )


def _read_dsm_metadata(dsm_path: Path) -> dict | None:
    """
    Read spatial metadata from the DSM GeoTIFF.

    Args:
        dsm_path: Path to DSM

    Returns:
        Dict with width, height, geotransform, projection (or None)
    """
    if gdal is None:
        raise RuntimeError("GDAL Python bindings are required")

    ds = gdal.Open(str(dsm_path), gdal.GA_ReadOnly)
    if ds is None:
        return None

    info = {
        "path": str(dsm_path),
        "width": ds.RasterXSize,
        "height": ds.RasterYSize,
        "geotransform": ds.GetGeoTransform(),
        "projection": ds.GetProjection(),
    }

    # Build a coverage mask: True where the DSM has valid (non-nodata) data.
    # This is used to clip band orthos to the actual field extent so the output
    # matches the RGB orthomosaic boundary instead of filling the whole bounding box.
    #
    # The mask is eroded by _DSM_MASK_EROSION_PX pixels before use so that the
    # noisy perimeter of the point cloud (sparse image overlap at field edges
    # causes COLMAP to produce artefacted depth estimates) is excluded.  The
    # erosion removes the radial streaking visible in hillshade and band outputs.
    try:
        band = ds.GetRasterBand(1)
        dsm_nd = band.GetNoDataValue()
        dsm_data = band.ReadAsArray()
        if dsm_nd is not None:
            coverage = (dsm_data != dsm_nd) & np.isfinite(dsm_data.astype(np.float32))
        else:
            coverage = np.isfinite(dsm_data.astype(np.float32))

        # Terrain elevation — median of valid DSM pixels before erosion.
        # Used by _extract_agl_and_hfov to convert AMSL GPS altitude to AGL.
        valid_elev = dsm_data[coverage].astype(np.float32)
        info["mean_elevation"] = float(np.median(valid_elev)) if valid_elev.size else 0.0

        try:
            from scipy.ndimage import binary_erosion
            coverage = binary_erosion(coverage, iterations=_DSM_MASK_EROSION_PX)
        except ImportError:
            logger.debug(
                "scipy not available — DSM coverage mask erosion skipped; "
                "perimeter reconstruction artefacts may appear in outputs"
            )
        info["coverage_mask"] = coverage
    except Exception:
        info["coverage_mask"] = None  # proceed without clipping if read fails
        info.setdefault("mean_elevation", 0.0)

    ds = None

    if not info["projection"]:
        logger.error(
            f"DSM at {dsm_path} has no CRS (empty projection). "
            "geo-registration (model_aligner) likely failed during SFM — "
            "geo_reference.json was not written. "
            "GPS-guided band orthorectification cannot proceed without a valid target SRS. "
            "Re-run the job after the geo_register fix is deployed."
        )
        return None

    return info


def _run_cmd(cmd: list[str], description: str) -> None:
    """
    Execute a shell command and raise on failure.

    Args:
        cmd: Command tokens
        description: Human-readable label for logging
    """
    logger.info(f"Running: {description}")
    logger.debug(f"Command: {' '.join(cmd)}")
    result = subprocess.run(cmd, check=True, capture_output=True, text=True)
    if result.stdout:
        logger.debug(f"stdout: {result.stdout[:500]}")
