# Generated by Django 5.1.14 on 2025-12-02 18:47

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('capture_start', models.DateTimeField(blank=True, null=True)),
                ('capture_end', models.DateTimeField(blank=True, null=True)),
                ('crs', models.CharField(blank=True, default='EPSG:4326', max_length=100, null=True)),
                ('bbox', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='accounts.organization')),
            ],
            options={
                'db_table': 'uploads_datasets',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id', models.IntegerField(help_text='ID of the user who uploaded')),
                ('file_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(default='application/octet-stream', max_length=100)),
                ('s3_key', models.CharField(max_length=1024)),
                ('file_size', models.BigIntegerField(blank=True, help_text='Size of the file in bytes', null=True)),
                ('batch_id', models.UUIDField(blank=True, help_text='Unique ID for the upload session/batch', null=True)),
                ('file_type', models.CharField(choices=[('IMAGE', 'Image'), ('ARCHIVE', 'Archive')], default='IMAGE', help_text='Distinguishes between single images and archives (zip)', max_length=20)),
                ('checksum', models.CharField(blank=True, max_length=255, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('exif', models.JSONField(blank=True, default=dict)),
                ('imu', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='uploads.dataset')),
                ('parent_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='uploads.image')),
            ],
            options={
                'db_table': 'uploads_images',
            },
        ),
    ]
