# Generated by Django 5.1.14 on 2025-12-02 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The status code, e.g., 'PENDING'", max_length=50, unique=True)),
                ('label', models.CharField(help_text="A human-readable label, e.g., 'Pending'", max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Upload Statuses',
                'db_table': 'uploads_statuses',
            },
        ),
        migrations.AlterField(
            model_name='image',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='uploads.uploadstatus'),
        ),
    ]
