# Generated by Django 5.1.14 on 2025-12-02 18:51

from django.db import migrations

STATUSES = [
        {'name': 'PENDING', 'label': 'Pending'},
        {'name': 'PROCESSING', 'label': 'Processing'},
        {'name': 'COMPLETED', 'label': 'Completed'},
        {'name': 'FAILED', 'label': 'Failed'},

    ]

def populate_statuses(apps, schema_editor):
        """
        Creates the initial set of upload statuses in the database.
        """
        UploadStatus = apps.get_model('uploads', 'UploadStatus')
        for status_data in STATUSES:
            UploadStatus.objects.get_or_create(name=status_data['name'], defaults={'label': status_data['label']})

class Migration(migrations.Migration):
    dependencies = [
        ('uploads', '0002_uploadstatus_alter_image_status'),
    ]

    operations = [
        migrations.RunPython(populate_statuses, reverse_code=migrations.RunPython.noop),
    ]
