# Generated by Django 5.1.14 on 2025-12-03 05:53

import apps.uploads.infrastructure.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_populate_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='status',
            field=models.ForeignKey(blank=True, default=apps.uploads.infrastructure.models.get_default_status, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='uploads.uploadstatus'),
        ),
        migrations.AlterField(
            model_name='image',
            name='user_id',
            field=models.BigIntegerField(help_text='ID of the user who uploaded'),
        ),
        migrations.CreateModel(
            name='AIProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_id', models.UUIDField(blank=True, help_text='Batch ID provided by frontend', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to='uploads.dataset')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_jobs', to='uploads.uploadstatus')),
            ],
        ),
        migrations.CreateModel(
            name='AIResultFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('s3_key', models.CharField(max_length=1000)),
                ('file_type', models.CharField(max_length=50)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='uploads.aiprocessingjob')),
            ],
        ),
    ]
