# Generated by Django 5.1.14 on 2025-12-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_alter_image_status_alter_image_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user_id',
        ),


        migrations.AddField(
            model_name='image',
            name='user_id',
            field=models.UUIDField(help_text='ID of the user who uploaded', null=True, blank=True),
        ),
    ]