# Generated by Django 5.1.14 on 2025-12-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0005_alter_image_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='s3_upload_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='user_id',
            field=models.UUIDField(default='00000000-0000-0000-0000-000000000000', help_text='ID of the user who uploaded'),
            preserve_default=False,
        ),
    ]
