# Generated by Django 5.2.12 on 2026-03-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0008_add_downloading_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if upload/processing failed', null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='file_type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('ARCHIVE', 'Archive'), ('METADATA', 'Metadata')], default='IMAGE', help_text='Distinguishes between single images and archives (zip)', max_length=20),
        ),
    ]
