# Generated by Django 5.1.14 on 2025-11-27 08:41

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('secret', models.CharField(blank=True, max_length=255, verbose_name='Secret Key')),
                ('events', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='List of events this webhook subscribes to.', size=None)),
                ('active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(db_column='org_id', on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Webhook Endpoint',
                'verbose_name_plural': 'Webhook Endpoints',
                'db_table': 'webhooks',
                'ordering': ['-created_at'],
            },
        ),
    ]
