# Generated by Django 5.1.14 on 2025-11-28 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('fmis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookendpoint',
            name='org',
            field=models.ForeignKey(db_column='org_id', on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='accounts.organization', verbose_name='Organization'),
        ),
        migrations.AlterModelTable(
            name='webhookendpoint',
            table='fmis_webhook',
        ),
    ]
