# Generated by Django 5.1.14 on 2025-12-27 14:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20251214_2246'),
        ('fmis', '0002_alter_webhookendpoint_org_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookendpoint',
            name='headers',
            field=models.JSONField(blank=True, default=dict, help_text="Custom HTTP headers (e.g., {'Authorization': 'Bearer <token>'})", verbose_name='Custom Headers'),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result_data', models.JSONField(blank=True, null=True, verbose_name='Result Data')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(db_column='org_id', on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'fmis_job',
                'ordering': ['-created_at'],
            },
        ),
    ]
