# Generated by Django 5.1.14 on 2025-12-27 19:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20251214_2246'),
        ('fmis', '0003_webhookendpoint_headers_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookendpoint',
            name='headers',
            field=models.JSONField(blank=True, default=dict, verbose_name='Custom Headers'),
        ),
        migrations.CreateModel(
            name='FMISIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_name', models.CharField(help_text='Destination system name, e.g., Farm-b', max_length=100)),
                ('base_url', models.URLField(help_text='Base API URL')),
                ('api_token', models.CharField(help_text='Authentication Token', max_length=500)),
                ('extra_headers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fmis_integrations', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'External Integration',
                'verbose_name_plural': 'External Integrations',
                'unique_together': {('org', 'provider_name')},
            },
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
