# Generated by Django 5.1.14 on 2025-12-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmis', '0004_alter_webhookendpoint_headers_fmisintegration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fmisintegration',
            name='api_token',
            field=models.CharField(help_text='Authentication Token / API Key', max_length=500),
        ),
        migrations.AlterField(
            model_name='fmisintegration',
            name='base_url',
            field=models.URLField(help_text='Base API URL provided by the external system'),
        ),
        migrations.AlterField(
            model_name='fmisintegration',
            name='provider_name',
            field=models.CharField(choices=[('farm_b', 'Farm-b'), ('leaf', 'Leaf Agriculture'), ('timberlee', 'Timberlee'), ('generic', 'Generic / Custom')], default='generic', help_text='Select the external system provider', max_length=50),
        ),
    ]
