# Generated by Django 5.1.14 on 2025-11-28 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmis', '0002_alter_webhookendpoint_org_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
